version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID:
        USER_GID:
    init: true
    volumes:
      - ..:/workspace:cached
      - bundle:/usr/local/bundle
    command: sleep infinity 
    ports:
      - 3000:4567
      - 5000:5000
      - 35729:35729

volumes:
  bundle:
